##################################################################################################
# kafka client
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: kafkaclient
  labels:
    app: kafkaclient
spec:
  ports:
  - name: tcp
    port: 9092
    targetPort: 9092
    name: http
  selector:
    app: kafkaclient
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafkaclient
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafkaclient
    spec:
      containers:
      - name: kafkaclient
        image: morvencao/kafka-client:v1
        args: ['-kafka-server-address', '9.30.212.236', '-kafka-port', '9092']
        imagePullPolicy: IfNotPresent
---
