---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: quay.io/morvencao/webserver:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - readOnly: true
          mountPath: /certs
          name: certs
      volumes:
      - name: certs
        secret:
          secretName: webserver-certs
---
apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    app: webserver
    service: webserver
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: webserver-certs
spec:
  ports:
  - port: 8080
    name: https
  selector:
    app: webserver
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: webserver
  name: webserver
spec:
  port:
    targetPort: https
  tls:
    termination: reencrypt
  to:
    kind: Service
    name: webserver
    weight: 100
  wildcardPolicy: None
