apiVersion: v1
kind: Service
metadata:
  name: {{ template "shadowsocks.fullname" . }}
  labels:
    app: {{ template "shadowsocks.name" . }}
    chart: {{ template "shadowsocks.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8388
  selector:
    app: {{ template "shadowsocks.name" . }}
    release: {{ .Release.Name }}
