apiVersion: v1
kind: Service
metadata:
  name: istio-pilot-ilb
  namespace: istio-system
  labels:
    istio: pilot
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    name: http-pilot
    protocol: TCP
  - port: 15010
    name: grpc-pilot
    protocol: TCP
  - port: 15011
    name: tls-grpc-pilot
    protocol: TCP
  - port: 9093
    name: http-monitoring
  selector:
    istio: pilot
---
apiVersion: v1
kind: Service
metadata:
  name: dns-ilb
  namespace: kube-system
  labels:
    app: kube-dns
spec:
  type: LoadBalancer
  ports:
  - port: 53
    protocol: UDP
  selector:
    app: kube-dns
---
apiVersion: v1
kind: Service
metadata:
  name: mixer-ilb
  namespace: istio-system
  labels:
    istio: mixer
spec:
  type: LoadBalancer
  ports:
  - name: grpc-mixer-mtls
    port: 15004
  - name: grpc-mixer
    port: 9091
  - name: http-monitoring
    port: 9093
  - name: prometheus
    port: 42422
  selector:
    istio: mixer
    istio-mixer-type: telemetry
# This points to istio-telemetry until we are able to support both
# istio-policy and istio-telemetry as separate services for mesh expansion.
---
apiVersion: v1
kind: Service
metadata:
  name: citadel-ilb
  namespace: istio-system
  labels:
    istio: citadel
spec:
  type: LoadBalancer
  ports:
  - name: grpc-citadel
    port: 8060
    protocol: TCP
  - name: http-monitoring
    port: 9093
  selector:
    istio: citadel
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: istio-system
  labels:
    app: jaeger
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    app: jaeger
